### ISSUE TITLE
How is redirect to twitter working

### ISSUE THREAD

**Issue by alephzed** [spring-guides/gs-accessing-twitter#10]
In your twitterConnect.html, you have <form action="/connect/twitter" method="POST">,
What controller is handling the post in order to redirect the request to twitter? When I run this example, I am not getting redirected to twitter. Any ideas?

**Comment by gregturn** [comment]
@habuma Can you look into this when you get some time?

**Comment by alephzed** [comment]
Ok, actually it is a twitter configuration issue. If the callback URL is left empty, then it seems to fail. I don't have the need for a callback url, but if I put any url in there, the example works.
